// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQM5AgZ53fIQYun3gdNSBfCG-_69Nkld8',
    appId: '1:616337186483:web:d18da56f0dfd5828965ac6',
    messagingSenderId: '616337186483',
    projectId: 'nursing-care-app-702b7',
    authDomain: 'nursing-care-app-702b7.firebaseapp.com',
    storageBucket: 'nursing-care-app-702b7.firebasestorage.app',
    measurementId: 'G-SDTQX99TV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlc72H773aV8Tfpb_Harzd7hx4bN7MyZw',
    appId: '1:616337186483:android:d8d33a1f02fff019965ac6',
    messagingSenderId: '616337186483',
    projectId: 'nursing-care-app-702b7',
    storageBucket: 'nursing-care-app-702b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8qdbPL5aCizzPMZllHPWVJKJxprd82bU',
    appId: '1:616337186483:ios:da0c7f2fd09e9326965ac6',
    messagingSenderId: '616337186483',
    projectId: 'nursing-care-app-702b7',
    storageBucket: 'nursing-care-app-702b7.firebasestorage.app',
    iosBundleId: 'com.example.nursingCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8qdbPL5aCizzPMZllHPWVJKJxprd82bU',
    appId: '1:616337186483:ios:da0c7f2fd09e9326965ac6',
    messagingSenderId: '616337186483',
    projectId: 'nursing-care-app-702b7',
    storageBucket: 'nursing-care-app-702b7.firebasestorage.app',
    iosBundleId: 'com.example.nursingCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQM5AgZ53fIQYun3gdNSBfCG-_69Nkld8',
    appId: '1:616337186483:web:d42632af4f36d02f965ac6',
    messagingSenderId: '616337186483',
    projectId: 'nursing-care-app-702b7',
    authDomain: 'nursing-care-app-702b7.firebaseapp.com',
    storageBucket: 'nursing-care-app-702b7.firebasestorage.app',
    measurementId: 'G-SB0WM6D0QH',
  );
}
